# Site settings
email: comm@aavv.io 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: ombreradio
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: aavv
profile_img: http://www.aavv.io/img/logo5.jpg
profile: 
social:
        github: https://github.com/auctores-varii

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
